# ==========================================
# appearance.toml
# ==========================================

[appearance]
prefer_no_csd = true
border_width = 3               # 0-100
outer_border_width = 1         # 0-100
corner_radius = 8
backdrop_color = "transparent"


