[appearance.blur]
enabled = true
optimized = true # false to no xray
passes = 4       # 0-8
radius = 6       # 0-100
noise = 0.02     # 0.0-1.0
brightness = 1.0 # 0.0-2.0
contrast = 1.0   # 0.0-2.0
saturation = 1.1 # 0.0-2.0

# ================ BLUR ================

[[window_rule]]
match.app_id = "(kitty|vesktop|Nautilus$|Loupe$|dev.noctalia.Noctalia|zen|^dev.zed)"
blur = true

# ── Noctalia shell ────
[[layer_rule]]
match.namespace = "^noctalia-(bar-[^\"]+|notification|dock|panel|attached-panel|osd|desktop-widget-[^\"]*)$"
blur = true
blur_optimized = false
blur_ignore_alpha = 0.5
blur_popups = true

# # ── Forced blur/opacity windows ────
# [[window_rule]]
# blur = true
# opacity = 0.8
