[include]
files = ["templates.toml"]

[audio]
enable_overdrive = true
enable_sounds = true
sound_volume = 1

# [control_center]

    [control_center.calendar]
    show_events_card = false

[battery]
warning_threshold = 20

[brightness]
minimum_brightness = 0.02

[control_center]

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "notification"

[desktop_widgets]
enabled = false

[dock]
inactive_scale = 1.0
launcher_position = "end"
show_dots = true

[nightlight]
temperature_night = 2000

[notification]
layer = "top"
position = "top_right"

[osd]
orientation = "vertical"
position_vertical = "center_right"


    [osd.kinds]
    media = false

[shell]
password_style = "random"
screen_time_enabled = true
settings_show_advanced = true

[shell.screenshot]
directory         = "~/Pictures/Screenshots/" # output folder; empty = ~/Pictures
filename_pattern  = "screenshot_%Y%m%d_%H%M%S" # strftime pattern, no extension (.png is added)

[shell.panel]
control_center_placement = "floating"
open_near_click_control_center = true
session_placement = "floating"
session_position = "center"
transparency_mode = "soft"
wallpaper_placement = "floating"
wallpaper_position = "center"

[shell.session]
grid = true

    [[shell.session.actions]]
    action = "command"
    command = "pkill noctalia&& sleep 0.2 && noctalia -d"
    countdown_seconds = 0.0
    enabled = true
    glyph = "reload"
    label = "Reiniciar Noctalia"
    variant = "default"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "l"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "x"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "s"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "r"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "p"
    variant = "destructive"

[theme.templates]
builtin_ids = [ "gtk3", "gtk4", "qt" ]

[widget.battery]
display_mode = "graphic"
enabled = true
show_label = true

[widget.clock]
format = "%a %e, %R"

[widget.input_volume]
show_label = false

[widget.media]
hide_when_no_media = false
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.privacy]
hide_inactive = true

[widget.session]
color = "error"

[widget.tray]
drawer = true

[widget.volume]
show_label = false
