[include]
# files = ["custom.toml"]
# [theme.templates.custom_colors]
# focus_ring = "#f97316" # focused window border

# ================
# templates.user
# ================

[theme.templates.user.fastfetch]
input_path = "templates/fastfetch.jsonc"
output_path = "$XDG_CONFIG_HOME/fastfetch/config.jsonc"

[theme.templates.user.ghostty]
input_path = "templates/template.ghostty"
output_path = "$XDG_CONFIG_HOME/ghostty/themes/Noctalia"
post_hook = "pgrep -f ghostty >/dev/null && pkill -SIGUSR2 ghostty || true"

[theme.templates.user.mpv]
input_path = "templates/mpv.conf"
output_path = "$XDG_CONFIG_HOME/mpv/script-opts/modernz.conf"

[theme.templates.user.niri]
input_path = "templates/niri.kdl"
output_path = "$XDG_CONFIG_HOME/niri/noctalia/colors.kdl"

[theme.templates.user.spicetify_comfy]
input_path = "templates/spicetify.ini"
output_path = "$XDG_CONFIG_HOME/spicetify/Themes/Comfy/color.ini"
post_hook = "~/.spicetify/spicetify -q apply --no-restart"

[theme.templates.user.starship]
input_path = "templates/starship.toml"
output_path = "$XDG_CONFIG_HOME/starship.toml"

[theme.templates.user.zathura]
input_path = 'templates/zathurarc'
output_path = '$XDG_CONFIG_HOME/zathura/zathurarc'

[theme.templates.user.zed]
input_path = "templates/zed.json"
output_path = "$XDG_CONFIG_HOME/zed/themes/noctalia.json"

[theme.templates.user.zen]
input_path = "templates/zen.css"
output_path = "$XDG_CONFIG_HOME/zen/profile.default/chrome/Noctalia.css"
# enabled = false

[theme.templates.user.showcase]
input_path = "templates/showcase.html"
output_path = "~/.dotfiles/Palette_Showcase.html"
