[include]
# files = ["custom.toml"]
# [theme.templates.custom_colors]
# focus_ring = "#f97316" # focused window border

# ================
# templates.user
# ================

[theme.templates.user.fastfetch]
input_path = "templates/fastfetch.jsonc"
output_path = "$XDG_CONFIG_HOME/fastfetch/config.jsonc"

[theme.templates.user.ghostty]
input_path = "../ghostty/template.ghostty"
output_path = "$XDG_CONFIG_HOME/ghostty/themes/Noctalia"
post_hook = "pgrep -f ghostty >/dev/null && pkill -SIGUSR2 ghostty || true"

[theme.templates.user.gtk3]
input_path = "templates/gtk3.css"
output_path = "$XDG_CONFIG_HOME/gtk-3.0/noctalia.css"
post_hook = "bash '/usr/share/noctalia/assets/templates/gtk/apply.sh' {{ mode }}"

[theme.templates.user.gtk4]
input_path = "templates/gtk4.css"
output_path = "$XDG_CONFIG_HOME/gtk-4.0/noctalia.css"
post_hook = "bash '/usr/share/noctalia/assets/templates/gtk/apply.sh' {{ mode }}"

[theme.templates.user.mpv]
input_path = "../mpv/temaplate.mpv.conf"
output_path = "$XDG_CONFIG_HOME/mpv/script-opts/modernz.conf"

[theme.templates.user.niri]
input_path = "templates/niri.kdl"
output_path = "$XDG_CONFIG_HOME/niri/noctalia/colors.kdl"

[theme.templates.user.spicetify_comfy]
input_path = "../spicetify/template.spicetify.ini"
output_path = "$XDG_CONFIG_HOME/spicetify/Themes/Comfy/color.ini"
post_hook = "~/.spicetify/spicetify -q apply --no-restart"

[theme.templates.user.starship]
input_path = "templates/starship.toml"
output_path = "$XDG_CONFIG_HOME/starship.toml"

[theme.templates.user.zathura]
input_path = 'templates/zathurarc'
output_path = '$XDG_CONFIG_HOME/zathura/zathurarc'

[theme.templates.user.zed]
input_path = "../zed/template.zed.json"
output_path = "$XDG_CONFIG_HOME/zed/themes/noctalia.json"

[theme.templates.user.zen]
input_path = "../zen/template.zen.css"
output_path = "$XDG_CONFIG_HOME/zen/profile.default/chrome/Noctalia.css"
# enabled = false

[theme.templates.user.showcase]
input_path = "templates/showcase.html"
output_path = "~/Dev/Palette_Showcase.html"
