# machines/vivbook.toml

[general]
autostart = [
  "noctalia",
  "sleep 5; filen-desktop",
  "easyeffects --hide-window",
]

[input.keyboard]
layout  = "br"
variant = "abnt2"   # XKB variant
options = ""        # XKB options, comma-separated

[events]
lid_close = "umbriel msg output-disable:eDP-1"
lid_open = "umbriel msg output-enable:eDP-1"
