# machines/nostromo.toml

[general]
autostart = [
    "noctalia",
    "sleep 5; filen-desktop",
    "easyeffects --hide-window",
    "flatpak run rocks.spotifast.Spotifast",
]

[input.keyboard]
layout  = "us"
variant = "altgr-intl"   # XKB variant
options = "compose:menu" # XKB options, comma-separated

[output."LG Electronics LG ULTRAGEAR 511AZGFGA247"]
mode = "2560x1440@165"
position = [0, 235]
scale = 1.0
vrr = "fullscreen"
hdr = "fullscreen"
sdr_white = 203
tearing = false
# workspaces = ["零", "一", "二", "三", "四", "五", "六", "七", "八", "九"]

[output."Samsung Electric Company LF24T35 HX5W300850"]
mode = "1920x1080@75"
position = [2560, 0]
scale = 1.0
transform = "270"
enabled = true
layout.scrolling.default_extent_fraction = 1
