# machines/nostromo.toml

[general]
autostart = [
    "noctalia",
    "vesktop --start-minimized",
    "sleep 5; filen",
    "spotify",
    "gnome-keyring-daemon --start --components=secrets"
]

[input.keyboard]
layout  = "us"
variant = "altgr-intl"   # XKB variant
options = "compose:menu" # XKB options, comma-separated

[output."LG Electronics LG ULTRAGEAR 511AZGFGA247"]
mode = "2560x1440@165"
position = [0, 330]
scale = 1.0
# workspaces = 5

[output."Samsung Electric Company LF24T35 HX5W300850"]
mode = "1920x1080@75"
position = [2560, 0]
scale = 1.0
transform = "270"
enabled = true
layout.scrolling.default_width_fraction = 1

[[workspace]]
index = 1
layout.mode = "dwindle"
output = "Samsung Electric Company LF24T35 HX5W300850"
