# ── Theme configuration ────────
include themes/Noctalia.conf

# ── Font configuration ────────
font_family      family="SauceCodePro Nerd Font" style="Medium"
bold_font        family="SauceCodePro Nerd Font" style="Bold"
italic_font      family="SauceCodePro Nerd Font" style="Italic"
bold_italic_font family="SauceCodePro Nerd Font" style="Bold Italic"
font_size        10.8
text_composition_strategy legacy
text_fg_override_threshold 1.5 ratio
linux_display_server wayland

# ── Terminal features ────────
mouse_hide_wait -1.0
confirm_os_window_close 0
inactive_text_alpha -0.5
enabled_layouts splits

# ── Shell Integration ────────
shell_integration no-cursor

# ── Window configuration ────────
hide_window_decorations yes
background_opacity 0.8
window_padding_width 12

# ── Cursor configuration ────────
cursor_shape beam
cursor_beam_thickness 1.5

# ── Keybinds ────────
map ctrl+comma edit_config_file
map ctrl+shift+r load_config_file
map ctrl+shift+backspace send_text all \x15
map ctrl+shift+y copy_last_command_output

map ctrl+shift+equal change_font_size all +1.5
map ctrl+shift+minus change_font_size all -1.5
map ctrl+0 change_font_size all 0

map f11 toggle_fullscreen
map f10 send_text all xdg-open . &\r

map ctrl+shift+q no_op

# ── Splits Creation ────────
map alt+r start_resizing_window
map alt+s launch --location=split --cwd=current

# Directional Splits
map alt+ctrl+up    launch --location=hsplit --cwd=current
map alt+ctrl+down  launch --location=hsplit --cwd=current
map alt+ctrl+left  launch --location=vsplit --cwd=current
map alt+ctrl+right launch --location=vsplit --cwd=current

# ── Split Navigation ────────
map alt+up    neighboring_window up
map alt+down  neighboring_window down
map alt+left  neighboring_window left
map alt+right neighboring_window right

# ── Window Movement ────────
map alt+shift+up    move_window up
map alt+shift+down  move_window down
map alt+shift+left  move_window left
map alt+shift+right move_window right
