[include]
files = ["templates.toml"]

[audio]
enable_overdrive = true

[backdrop]
enabled = true

[bar.default]
start = [ "launcher", "workspaces", "active_window" ]
center = [ "media" ]
end = [ "tray", "clipboard", "notifications", "privacy", "network", "bluetooth", "volume", "clock", "battery", "session" ]
font_family = "Adwaita Sans"
margin_edge = 0
panel_overlap = 0
margin_ends = 0
padding = 16
radius = 0
radius_bottom_left = -16
radius_bottom_right = -16
shadow = false

[battery]
warning_threshold = 20

[desktop_widgets]
enabled = false

[dock]
auto_hide = true
background_opacity = 1
cross_axis_padding = 4
enabled = true
inactive_opacity = 1
inactive_scale = 1.0
launcher_position = "end"
magnification_scale = 1.25
radius = 8
reserve_space = false
show_dots = true

[nightlight]
force = true
temperature_night = 2000

[notification]
layer = "top"
position = "top_right"

[osd]
orientation = "vertical"
position_vertical = "center_right"
background_opacity = 0.8


    [osd.kinds]
    media = false

[shell]
settings_show_advanced = true

    [shell.animation]
    speed = 1.5

    [shell.panel]
    floating_offset = 16
    wallpaper_placement = "floating"
    session_placement = "floating"
    control_center_placement = "attached"
    session_position = "center"
    transparency_mode = "soft"
    open_near_click_control_center = true
    open_near_click_session = true

    [shell.screen_corners]
    enabled = true

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "l"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "x"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "s"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "r"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "p"
    variant = "destructive"

[theme.templates]
builtin_ids = [ "gtk3", "gtk4", "qt" ]

[widget.active_window]
display = "icon_and_text"
title_scroll = "on_hover"
show_empty_label = true

[widget.battery]
display_mode = "graphic"
enabled = true
show_label = false

[widget.clock]
format = "{:%H:%M}"

[widget.launcher]
color = "primary"
custom_image_colorize = true

[widget.media]
anchor = true
hide_when_no_media = false
title_scroll = "on_hover"

[widget.privacy]
hide_inactive = true

[widget.session]
color = "error"

[widget.tray]
drawer = true

[widget.workspaces]
display = "none"
pill_scale = 0.9
capsule_padding = 6
capsule_radius = 30
inactive_pill_size = 1.0
occupied_color = "secondary"
empty_color = "outline"
