[include]
files = ["templates/"]

[audio]
enable_overdrive = true

[bar.default]
capsule = false
capsule_group = []
capsule_radius = 4
capsule_thickness = 0.7
center = [ "media" ]
end = [ "tray", "clipboard", "notifications", "privacy", "bluetooth", "network", "volume", "clock", "control-center" ]
font_family = "Adwaita Sans"
margin_edge = 0
margin_ends = 0
padding = 16
radius = 0
radius_bottom_left = -16
radius_bottom_right = -16
shadow = false
start = [ "workspaces", "active_window" ]

[battery]
warning_threshold = 20


[desktop_widgets]
enabled = false

[dock]
auto_hide = true
background_opacity = 1
cross_axis_padding = 4
enabled = true
inactive_opacity = 1
inactive_scale = 1.0
launcher_position = "end"
magnification_scale = 1.25
radius = 8
reserve_space = false
show_dots = true

[nightlight]
force = true
temperature_night = 2000

[notification]
layer = "top"
position = "top_right"

[osd]
orientation = "vertical"
position_vertical = "center_right"

    [osd.kinds]
    media = false

[shell]
settings_show_advanced = true

    [shell.animation]
    speed = 1.5

    [shell.panel]
    control_center_placement = "floating"
    floating_offset = 16
    open_near_click_control_center = true
    open_near_click_session = true
    session_placement = "floating"
    session_position = "center"
    wallpaper_placement = "floating"

    [shell.screen_corners]
    enabled = true

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "l"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "x"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "s"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "r"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "p"
    variant = "destructive"

[theme.templates]
builtin_ids = [ "gtk3", "gtk4", "qt" ]

[widget.active_window]
display = "icon_and_text"
icon_size = 16
max_length = 269
title_scroll = "on_hover"

[widget.clock]
format = "{:%H:%M}"

[widget.media]
art_size = 32
hide_when_no_media = true
title_scroll = "on_hover"

[widget.privacy]
hide_inactive = true

[widget.workspaces]
display = "none"
empty_color = "outline"
inactive_pill_size = 1.0
occupied_color = "tertiary"
pill_scale = 0.9
