# Custom colors
[include]
files = ["custom.toml"]
# [theme.templates.custom_colors]
# focus_ring = "#f97316" # focused window border

# ================
# theme.Templates
# ================

# Fastfetch
[theme.templates.user.fastfetch]
input_path = "templates/fastfetch.jsonc"
output_path = "$XDG_CONFIG_HOME/fastfetch/config.jsonc"

# Ghostty
[theme.templates.user.ghostty]
input_path = "templates/template.ghostty"
output_path = "$XDG_CONFIG_HOME/ghostty/themes/Noctalia"
post_hook = "pgrep -f ghostty >/dev/null && pkill -SIGUSR2 ghostty || true"

# MPV
[theme.templates.user.mpv]
input_path = "templates/mpv.conf"
output_path = "$XDG_CONFIG_HOME/mpv/script-opts/modernz.conf"

# Niri
[theme.templates.user.niri]
input_path = "templates/niri.kdl"
output_path = "$XDG_CONFIG_HOME/niri/noctalia.kdl"
post_hook = "niri msg action load-config-file"

# Spicetify
[theme.templates.user.spicetify]
input_path = "templates/spicetify.ini"
output_path = "$XDG_CONFIG_HOME/spicetify/Themes/Comfy/color.ini"
post_hook = "spicetify -q apply --no-restart"

# Starship
[theme.templates.user.ohmyposh]
input_path = "templates/starship.toml"
output_path = "$XDG_CONFIG_HOME/starship.toml"

# VSCodium
[theme.templates.user.vscodium]
input_path = "templates/vscodium.json"
output_path = "~/.vscode-oss/extensions/noctalia.noctaliatheme-0.0.5-universal/themes/NoctaliaTheme-color-theme.json"

# Zathura
[theme.templates.user.zathura]
input_path = 'templates/zathurarc'
output_path = '$XDG_CONFIG_HOME/zathura/zathurarc'

# Zen
[theme.templates.user.zen]
input_path = "templates/zen.css"
output_path = "$XDG_CONFIG_HOME/zen/profile.default/chrome/Noctalia.css"

[theme.templates.user.zen_chrome]
input_path = "templates/zen_chrome.css"
output_path = "$XDG_CONFIG_HOME/zen/profile.default/chrome/userChrome.css"

[theme.templates.user.zen_content]
input_path = "templates/zen_content.css"
output_path = "$XDG_CONFIG_HOME/zen/profile.default/chrome/userContent.css"

# HTML Preview
[theme.templates.user.preview]
input_path = "templates/preview.html"
output_path = "~/.dotfiles/previews/Showcase.html"
