# ============================================================
# Configuração do TemplateEngine do Noctalia
# ============================================================

# [config]
# Cores personalizadas (opcional)
# [config.custom_colors]
# brand = "#ff0000"

# ============================================================
# theme.Templates
# ============================================================

# Ghostty
[theme.templates.user.ghostty]
input_path = "shared/ghostty"
output_path = "$XDG_CONFIG_HOME/ghostty/themes/Noctalia"
post_hook = "pgrep -f ghostty >/dev/null && pkill -SIGUSR2 ghostty || true"

# MPV
[theme.templates.user.mpv]
input_path = "shared/mpv.lua"
output_path = "$XDG_CONFIG_HOME/mpv/scripts/colorscheme.lua"

# Niri
[theme.templates.user.niri]
input_path = "shared/niri.kdl"
output_path = "$XDG_CONFIG_HOME/niri/noctalia.kdl"

# Oh My Posh
[theme.templates.user.ohmyposh]
input_path = "shared/ohmyposh.template"
output_path = "$XDG_CONFIG_HOME/ohmyposh/ohmyposh.toml"
post_hook = "exec zsh; source $HOME/.zshrc"

# Spicetify
[theme.templates.user.spicetify]
input_path = "shared/spicetify.ini"
output_path = "$XDG_CONFIG_HOME/spicetify/Themes/comfy/color.ini"
post_hook = "spicetify -q apply --no-restart"

# Zen
[theme.templates.user.zen]
input_path = "shared/zen.css"
output_path = "$XDG_CONFIG_HOME/zen/profile.default/chrome/Noctalia.css"

[theme.templates.user.zen_chrome]
input_path = "shared/zen_chrome.css"
output_path = "$XDG_CONFIG_HOME/zen/profile.default/chrome/userChrome.css"

[theme.templates.user.zen_content]
input_path = "shared/zen_content.css"
output_path = "$XDG_CONFIG_HOME/zen/profile.default/chrome/userContent.css"