# ===========================================
# Configuração do TemplateEngine do Noctalia
# ===========================================

# add this to config.toml
# [include]
# files = ["templates/"]
# Cores personalizadas (opcional)
# [theme.templates.user.test]
# input_path = "templates/test.css"
# output_path = "~/test.css"

# ================
# theme.Templates
# ================

# Fastfetch
[theme.templates.user.fastfetch]
input_path = "templates/fastfetch.jsonc"
output_path = "$XDG_CONFIG_HOME/fastfetch/config.jsonc"

# Ghostty
[theme.templates.user.ghostty]
input_path = "templates/template.ghostty"
output_path = "$XDG_CONFIG_HOME/ghostty/themes/Noctalia"
post_hook = "pgrep -f ghostty >/dev/null && pkill -SIGUSR2 ghostty || true"

# MPV
[theme.templates.user.mpv]
input_path = "templates/mpv.conf"
output_path = "$XDG_CONFIG_HOME/mpv/script-opts/modernz.conf"

# Niri
[theme.templates.user.niri]
input_path = "templates/niri.kdl"
output_path = "$XDG_CONFIG_HOME/niri/noctalia.kdl"
post_hook = "niri msg action load-config-file"

# Oh My Posh
[theme.templates.user.ohmyposh]
input_path = "templates/ohmyposh.template"
output_path = "$XDG_CONFIG_HOME/ohmyposh/ohmyposh.toml"
post_hook = "oh-my-posh enable reload"

# Spicetify
[theme.templates.user.spicetify]
input_path = "templates/spicetify.ini"
output_path = "$XDG_CONFIG_HOME/spicetify/Themes/comfy/color.ini"
post_hook = "spicetify -q apply --no-restart"

[theme.templates.user.vscodium]
input_path = "templates/vscodium.json"
output_path = "~/.vscode-oss/extensions/noctalia.noctaliatheme-0.0.5-universal/themes/NoctaliaTheme-color-theme.json"

# Zen
[theme.templates.user.zen]
input_path = "templates/zen.css"
output_path = "$XDG_CONFIG_HOME/zen/profile.default/chrome/Noctalia.css"

[theme.templates.user.zen_chrome]
input_path = "templates/zen_chrome.css"
output_path = "$XDG_CONFIG_HOME/zen/profile.default/chrome/userChrome.css"

[theme.templates.user.zen_content]
input_path = "templates/zen_content.css"
output_path = "$XDG_CONFIG_HOME/zen/profile.default/chrome/userContent.css"
